#!/usr/bin/env sh

sudo apt-get update
sudo apt-get install -y zsh curl stow nodejs

export DOTFILES=~/.dotfiles
git clone https://github.com/Accumulative/dotfiles $DOTFILES

# zsh related installations
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh
cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
source ~/.zshrc
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

mkdir -p ~/.nvim/tmp/swap
mkdir -p ~/.nvim/tmp/undo
mkdir -p ~/.nvim/tmp/backup

sudo add-apt-repository ppa:mmstick76/alacritty
sudo apt install alacritty
npm install -g alacritty-themes
git clone https://github.com/alacritty/alacritty.git
sudo tic -xe alacritty,alacritty-direct alacritty/extra/alacritty.info
rm -rf alacritty
